import { Box, Divider, Flex, Link, Text } from "@chakra-ui/react";
import { useEffect } from "react";
import { THEME } from "../../../utils/const";
import PageWrapper from "../../components/pageWrapper";

const PrivacyPage = () => {
    useEffect(() => {
        window.document.title = "Privacy Policy | WhatsLeads";
        window.scroll(0, 0);
    }, []);
    return (
        <PageWrapper>
            <Flex
                direction={"column"}
                p={"1rem"}
                justifyContent={"center"}
                width={"full"}
            >
                <Flex
                    direction={"column"}
                    width={"90vw"}
                    maxWidth={"900px"}
                    mx={"auto"}
                >
                    <Text
                        fontSize={"3xl"}
                        py={"2rem"}
                        color={THEME.THEME_GREEN}
                    >
                        Privacy Policy
                    </Text>
                    <Box>
                        <Text fontSize={"xl"} fontWeight={"medium"}>
                            1. Is this Chrome Extension Safe?
                        </Text>
                        <Text pt={"1rem"}>
                            Yes, it is safe. We do not store any of your
                            personal data. All the files generated by the
                            extension are encrypted. Moreover, all Chrome store
                            extensions are reviewed manually by Google team
                            before they approve of them on the Chrome Web store.
                        </Text>
                    </Box>
                    <Divider my={"1rem"} />
                    <Box>
                        <Text fontSize={"xl"} fontWeight={"medium"}>
                            2. Is my phone number exposed to the extension
                            developers?
                        </Text>
                        <Text pt={"1rem"}>
                            No. The extension developers do not see any phone
                            numbers. In fact, we do not even ask for your phone
                            number when using this extension.
                        </Text>
                    </Box>
                    <Divider my={"1rem"} />
                    <Box>
                        <Text fontSize={"xl"} fontWeight={"medium"}>
                            3. Are my conversations, or my exported contacts
                            exposed to the extension developers, or any third
                            parties?
                        </Text>
                        <Text pt={"1rem"}>
                            No, the export features get the data from the WhatsApp web,
                            and saves it immediately to your computer, the data
                            is not exposed or processed anywhere outside your
                            computer.
                        </Text>
                    </Box>
                    <Divider my={"1rem"} />
                    <Box>
                        <Text fontSize={"xl"} fontWeight={"medium"}>
                            4. When purchasing a subscription, will my payment
                            information be safe?
                        </Text>
                        <Text pt={"1rem"}>
                            Statfluence processes all payments and credit card
                            data through Razorpay, a secure 3rd party service
                            that protects all your data and transactions.
                            Statfluence doesn’t store your payment information.
                        </Text>
                    </Box>
                    <Divider my={"1rem"} />
                    <Box>
                        <Text fontSize={"xl"} fontWeight={"medium"}>
                            5. Can I change my number or get a refund?
                        </Text>
                        <Text pt={"1rem"}>
                            Users are not able to change their subscribed
                            numbers, and refunds are not provided. Please reach
                            out to customer support for more help on this at
                            <Link href="https://api.whatsapp.com/send/?phone=919654308000&text&type=phone_number&app_absent=0" color="green.400" _hover={{color:"green.300"}} target="_blank"> wa.me/9654308000</Link>
                        </Text>
                    </Box>
                </Flex>
            </Flex>
        </PageWrapper>
    );
};

export default PrivacyPage;
