export { default as FILE } from './images/file.png';
export { default as GREEN_SHADOW } from './images/green-shadow.png';
export { default as LOGO } from './images/logo.svg';
export { default as NETWORK_ERROR } from './images/network-error.png';
export { default as NETWORK_ERROR_SVG } from './images/network-error.svg';
export { default as USER } from './images/user.png';
export { default as WA_AUTH } from './images/wa-auth.jpg';
export { default as WA_DEVICE } from './images/wa-device.jpeg';
export { default as WELCOME_TYPING } from './images/welcome-typing.png';
