module.exports = {
	Base: require('./Base.js'),
	BusinessContact: require('./BusinessContact.js'),
	Chat: require('./Chat.js'),
	ClientInfo: require('./ClientInfo.js'),
	Contact: require('./Contact.js'),
	GroupChat: require('./GroupChat.js'),
	Location: require('./Location.js'),
	Message: require('./Message.js'),
	MessageMedia: require('./MessageMedia.js'),
	PrivateChat: require('./PrivateChat.js'),
	PrivateContact: require('./PrivateContact.js'),
	GroupNotification: require('./GroupNotification.js'),
	Label: require('./Label.js'),
	Order: require('./Order.js'),
	Product: require('./Product.js'),
	Call: require('./Call.js'),
	Buttons: require('./Buttons.js'),
	List: require('./List.js'),
	Payment: require('./Payment.js'),
	Reaction: require('./Reaction.js'),
	Poll: require('./Poll.js'),
	PollVote: require('./PollVote.js'),
};
