import { Box, Flex, Text } from "@chakra-ui/react";
import PageWrapper from "../components/pageWrapper";

const Terms = () => {
    return (
        <PageWrapper>
            <Flex direction={"column"} gap={"2rem"} p={"1rem"}>
                <Text fontSize={"2xl"}>Privacy Policy</Text>
                <Box>
                    <Text>1. Is this Chrome Extension Safe?</Text>
                    <Text>
                        Yes, it is safe. We do not store any of your personal
                        data. All the files generated by the extension are
                        encrypted. Moreover, all Chrome store extensions are
                        reviewed manually by Google team before they approve of
                        them on the Chrome Web store. Also we are using
                        AWS(Amazon Web Services) for your data security.
                    </Text>
                </Box>
                <Box>
                    <Text>
                        2. Is my phone number exposed to the extension
                        developers?
                    </Text>
                    <Text>
                        No. The extension developers do not see any phone
                        numbers. In fact, we do not even ask for your phone
                        number when using this extension.
                    </Text>
                </Box>
                <Box>
                    <Text>
                        3. Are my conversations, or my exported contacts exposed
                        to the extension developers, or any third parties?
                    </Text>
                    <Text>
                        No, the export features get the data from the AWS, and
                        saves it immediately to your computer, the data is not
                        exposed or processed anywhere outside your computer.
                    </Text>
                </Box>
                <Box>
                    <Text>
                        4. When purchasing a subscription, will my payment
                        information be safe?
                    </Text>
                    <Text>
                        Statfluence processes all payments and credit card data
                        through Razorpay, a secure 3rd party service that
                        protects all your data and transactions. Statfluence
                        doesn’t store your payment information.
                    </Text>
                </Box>
                <Box>
                    <Text>5. Can I change my number or get a refund?</Text>
                    <Text>
                        Users are not able to change their subscribed numbers,
                        and refunds are not provided. Please reach out to
                        customer support for more help on this at
                        wa.me/16507312588
                    </Text>
                </Box>
            </Flex>
        </PageWrapper>
    );
};

export default Terms;
