export { default as ENHANCHMENT } from "./images/ENHANCHMENT.png";
export { default as EXPORT } from "./images/EXPORT.png";
export { default as PAYMENT } from "./images/Payment process.png";
export { default as REPORT } from "./images/REPORT.png";
export { default as SCREEN_SHOT } from "./images/SS.png";
export { default as CHROME_GREEN } from "./images/chrome-green.svg";
export { default as CHROME } from "./images/chrome.svg";
export { default as FACEBOOK } from "./images/facebook.svg";
export { default as BACKGROUND } from "./images/footer image.svg";
export { default as MENU } from "./images/hamburger.svg";
export { default as HERO_BG } from "./images/image 1.png";
export { default as INSTAGRAM } from "./images/instagram.svg";
export { default as LOGO } from "./images/logo.svg";
export { default as RATING } from "./images/rating.png";
export { default as CUSTOMER } from "./images/service.png";
export { default as TRANSACTION } from "./images/transaction.png";
export { default as TWITTER } from "./images/twitter.svg";
export { default as WHATSAPP } from "./images/whatsapp.svg";
